### ISSUE TITLE
Add mini-map button

### ISSUE THREAD

**Issue by andybergon** [AzerPUG/Renown-Checker#4]
It would be nice to not have to remember the incantation `/azp rc` to open the addon but have either a mini-map button or an entry in the interface menu.

**Comment by Arco-Dielhof** [comment]
Heyy! I am currently very busy, so getting this done within a few days (which I normally would) sadly is not going to work. However, I have added it to my March Goals, so there is a pretty decent chance it will happen within March (Yes, March 2022 :P )

Thank you for the suggestion! :D

**Comment by Arco-Dielhof** [comment]
Add the AddOn to AzerPUG's Core, to temporarily semi-fix this.
Find a way to display a clickable mini-map like button without the need for an extremely huge, bloat library (So not Ace... xD )
